### ISSUE TITLE
Define a way to store shoes images in the database

### ISSUE THREAD

**Issue by nomicos** [ebiz-bebeka/ebiz-app#26]
I think storing filenames (or relative path) of the images is good.

See also:  
https://stackoverflow.com/questions/3748/storing-images-in-db-yea-or-nay

**Comment by JellyKoala** [comment]
I've read a bit about it and I think storing path to photos is the most simple and best option.

**Comment by JellyKoala** [comment]
I think it's decided that we store relative paths to pictures in database. I propose closing this issue.

**Comment by nomicos** [comment]
Path or just filenames though? I think all the shoes images will be stored in one directory anyway.
