### ISSUE TITLE
Create complete relational database

### ISSUE THREAD

**Issue by JellyKoala** [ebiz-bebeka/ebiz-app#27]
Create all classes needed for store to be functional.

**Comment by JellyKoala** [comment]
![db_model](https://user-images.githubusercontent.com/36109622/41322247-44f0d738-6ea8-11e8-88ec-6ab23d7dd7c3.PNG)

**Comment by JellyKoala** [comment]
Does anyone has any remarks?

**Comment by JellyKoala** [comment]
![db_ebiz-bbk](https://user-images.githubusercontent.com/36109622/41334785-0ec07dfa-6ee7-11e8-988d-26c6c9ed3d8a.PNG)


Corrected database schema.

**Comment by szymonb95** [comment]
IDs which are primary keys choud be named as just 'id'. If we know table, then we know of what ID it is.

**Comment by JellyKoala** [comment]
![db_ebiz-bbk](https://user-images.githubusercontent.com/36109622/41338551-ce128bb6-6ef2-11e8-90c3-40a97946ea68.PNG)

Database model - final version

**Comment by JellyKoala** [comment]
![db_ebiz-bbk](https://user-images.githubusercontent.com/36109622/41339128-66101982-6ef4-11e8-909e-6e9d5b8de534.PNG)

Database model - final version

**Comment by JellyKoala** [comment]
New tables:

CREATE TABLE sales_shopping_cart(
	"id" int NOT NULL PRIMARY KEY,
	price double,
	paid boolean,
	order_date date,
	payment_date date
)

CREATE TABLE sales_order(
	"id" int NOT NULL PRIMARY KEY,
	quantity int
)

CREATE TABLE customer_customer(
	"id" int NOT NULL PRIMARY KEY,
	name varchar(25) NOT NULL,
	surname varchar(25) NOT NULL,
	email varchar(60),
	phone varchar(13),
	address_line_1 varchar(127),
	username varchar(25),
	"password" varchar(25)
)

CREATE TABLE customer_country(
	"id" int NOT NULL PRIMARY KEY,
	name varchar(25)
)

CREATE TABLE customer_city(
	"id" int NOT NULL PRIMARY KEY,
	name varchar(40)
)


Foreign keys:

ALTER TABLE sales_order
ADD CONSTRAINT FK_shoes_model
FOREIGN KEY shoes_model_id REFERENCES shoes_model(id);

ALTER TABLE sales_order
ADD CONSTRAINT FK_sales_shopping_cart
FOREIGN KEY shopping_cart_id REFERENCES sales_shopping_cart(id);

ALTER TABLE sales_shopping_cart
ADD CONSTRAINT FK_customer_customer
FOREIGN KEY customer_id REFERENCES customer_customer(id);

ALTER TABLE customer_customer
ADD CONSTRAINT FK_customer_city
FOREIGN KEY customer_city_id REFERENCES customer_city(id);

ALTER TABLE customer_city
ADD CONSTRAINT FK_customer_country
FOREIGN KEY customer_country_id REFERENCES customer_country(id);
